import en from "@/locales/en/translation";
import pt from "@/locales/pt/translation";
import type { Project } from "./projects";

type Study = { role: string; team?: string; context?: string; story: string[] };

const studies: Record<string, Record<"en" | "pt", Study>> = {
  "racing-game": {
    en: { role: "Development with AI", team: "Solo", context: "Personal project", story: ["I built Kart Island with AI as a personal project, to see how far a new model could take a real-time multiplayer game. Later, when GPT-6 Astra became better at building objects in Blender, I used it to fill the world with more 3D models.", "The server is authoritative. It runs the race at a fixed 60 ticks per second and owns movement, collisions, laps and standings, while players only send their controls. The track, physics and race rules live in shared code with no framework, so the server and the browser run exactly the same simulation.", "To keep driving responsive despite network delay, the browser predicts your own kart and corrects it against snapshots the server sends 20 times a second, and draws the other karts from a short buffer of snapshots so they move smoothly. Computer drivers use the same karts and rules as players, and a seeded test run across every track and difficulty checks them before changes ship."] },
    pt: { role: "Desenvolvimento com IA", team: "Individual", context: "Projeto pessoal", story: ["Desenvolvi o Kart Island com IA como projeto pessoal, para ver até onde um novo modelo conseguia levar um jogo multijogador em tempo real. Mais tarde, quando o GPT-6 Astra se tornou melhor a construir objetos no Blender, usei-o para encher o mundo com mais modelos 3D.", "O servidor é autoritativo. Corre a corrida a 60 ticks por segundo e controla o movimento, as colisões, as voltas e a classificação, enquanto os jogadores apenas enviam os seus comandos. A pista, a física e as regras da corrida vivem em código partilhado sem framework, pelo que o servidor e o browser correm exatamente a mesma simulação.", "Para a condução continuar responsiva apesar da latência, o browser prevê o movimento do teu kart e corrige-o com os snapshots que o servidor envia 20 vezes por segundo, e desenha os outros karts a partir de um pequeno buffer de snapshots para que se movam de forma fluida. Os pilotos controlados pelo computador usam os mesmos karts e regras que os jogadores, e uma bateria de testes com seeds em todas as pistas e dificuldades verifica-os antes de cada alteração."] },
  },
  "water-wise": {
    en: { role: "Co-developer", team: "2 people", context: "Final-year project", story: ["Water Wise was my final-year project in Computer Engineering at Universidade Lusófona, a decision-support platform to help farmers, water managers and researchers follow the state of Portugal's reservoirs. I built it with a classmate, starting from a Figma prototype and working in sprints on Trello. We mostly built it together, sometimes each taking charge of a page, reviewing each other's code and designing the interface side by side.", "The project came from the university's Faculty of Engineering, as the web platform of a wider European water management proposal. Two professors supervised us, and our contact at the Faculty of Engineering, an expert in time-series data, acted as our stakeholder, explaining what the platform needed and helping us get the data. After we finished, the platform was renamed Harmonia and presented and approved as part of that European initiative.", "The data comes from several places, including a weather station API, telemetry in InfluxDB, satellite imagery and other groups' predictive models. Station and database requests go through Next.js API routes, so credentials stay on the server. On the client, React Query caches data in IndexedDB so returning to a page is instant, Convex powers real-time alerts, Clerk handles sign-in, and the interface works in English and Portuguese.", "We tested it through two rounds of surveys with people who work in this area and would use a platform like it."] },
    pt: { role: "Co-desenvolvimento", team: "2 pessoas", context: "Projeto final de licenciatura", story: ["O Water Wise foi o meu projeto final de licenciatura em Engenharia Informática na Universidade Lusófona, uma plataforma de apoio à decisão para ajudar agricultores, gestores de recursos hídricos e investigadores a acompanhar o estado das albufeiras em Portugal. Desenvolvi-o com um colega de curso, a partir de um protótipo em Figma e a trabalhar em sprints no Trello. Construímo-lo sobretudo em conjunto, às vezes com cada um responsável por uma página, a rever o código um do outro e a desenhar a interface lado a lado.", "O projeto nasceu de um pedido da Faculdade de Engenharia da universidade, como a plataforma web de uma proposta europeia mais ampla de gestão da água. Dois professores orientaram-nos, e o nosso contacto na Faculdade de Engenharia, especialista em dados temporais, fez de stakeholder, a explicar o que a plataforma precisava e a ajudar-nos a obter os dados. Depois de terminarmos, a plataforma foi renomeada Harmonia e apresentada e aprovada como parte dessa iniciativa europeia.", "Os dados vêm de várias fontes, incluindo uma API de estações meteorológicas, telemetria em InfluxDB, imagens de satélite e modelos preditivos de outros grupos. Os pedidos às estações e à base de dados passam por API routes do Next.js, para que as credenciais fiquem no servidor. No cliente, o React Query guarda os dados em cache no IndexedDB para que voltar a uma página seja instantâneo, o Convex trata dos alertas em tempo real, o Clerk da autenticação, e a interface funciona em português e inglês.", "Testámo-la com duas rondas de inquéritos a pessoas que trabalham nesta área e usariam uma plataforma assim."] },
  },
  yoke: {
    en: { role: "Co-developer", team: "2 people", context: "Side project", story: ["Yoke started during my final year at university, around the time our classes were introducing Flutter. My friend and I were convinced React Native was the better choice, and since we were already writing React every day in Next.js for our final-year project, it felt familiar from the first screen.", "We planned a full fitness app covering workouts, nutrition, history and progress, and built it with Expo and Expo Router, with a tab for each area. The part we took furthest was the exercise library, a filterable catalogue with a detail page for every exercise, where people can also add their own exercises and keep them on their phone."] },
    pt: { role: "Co-desenvolvimento", team: "2 pessoas", context: "Projeto paralelo", story: ["O Yoke começou no meu último ano da licenciatura, mais ou menos quando as aulas começaram a introduzir o Flutter. Eu e o meu amigo estávamos convencidos de que o React Native era a melhor escolha e, como já escrevíamos React todos os dias em Next.js no nosso projeto final, pareceu-nos familiar desde o primeiro ecrã.", "Planeámos uma aplicação de fitness completa, com treinos, nutrição, histórico e progresso, e construímo-la com Expo e Expo Router, com um separador para cada área. A parte que levámos mais longe foi a biblioteca de exercícios, um catálogo com filtros e uma página de detalhe para cada exercício, onde também é possível adicionar exercícios próprios e guardá-los no telemóvel."] },
  },
  "emoji-puzzle": {
    en: { role: "Developer", team: "Solo", context: "Personal project", story: ["Yoke turned out to be really ambitious, so I wanted to try React Native again with something small enough to finish. Emoji Puzzle is a guessing game where each puzzle is a row of emojis hiding the title of a game, movie or song.", "The trickiest part was deciding when a guess counts. Instead of demanding an exact match, the answer checker compares the guess word by word and tolerates small differences like plurals or verb endings, so it can reply Correct, Near or Wrong. Hints reveal the category first and then more of the answer after each miss, stats and streaks are saved on the phone, and the game logic lives in a hook and a context, separate from the screens."] },
    pt: { role: "Desenvolvimento", team: "Individual", context: "Projeto pessoal", story: ["O Yoke acabou por ser muito ambicioso, por isso quis voltar a experimentar React Native com algo pequeno o suficiente para terminar. O Emoji Puzzle é um jogo de adivinhas em que cada puzzle é uma fila de emojis que esconde o título de um jogo, filme ou música.", "A parte mais difícil foi decidir quando é que uma resposta conta. Em vez de exigir uma correspondência exata, o verificador compara a resposta palavra a palavra e tolera pequenas diferenças, como plurais ou terminações verbais, para poder responder Certo, Perto ou Errado. As dicas revelam primeiro a categoria e depois mais da resposta a cada erro, as estatísticas e sequências ficam guardadas no telemóvel, e a lógica do jogo vive num hook e num context, separada dos ecrãs."] },
  },
  "live-notes": {
    en: { role: "Developer", team: "Solo", context: "Personal project", story: ["After using Convex for real-time alerts in my final-year project and enjoying it, I wanted to see how Firebase handles the same problem. Live Notes was the result, a shared board where everyone sees notes appear, move and change as they happen. It started out simple, and with the help of AI I grew it into the canvas it is now, with zooming, panning, a minimap and notes you can drag anywhere.", "Firebase's Realtime Database keeps a WebSocket open to every visitor and pushes changes the moment they are written, so each client listens to the board instead of asking for updates. Presence runs over the same connection, with Firebase removing a person automatically when their connection drops. Since the app was already on Firebase, I used its Google sign-in for accounts, while guests can still join anonymously, and usernames are claimed in transactions so two people can never take the same one.", "Edits go through server routes that validate them, and each save carries the text it was based on, so a conflicting edit is caught instead of silently overwriting someone else's. Unsaved changes wait in a queue that survives reloads and closed tabs, and the database security rules have their own tests."] },
    pt: { role: "Desenvolvimento", team: "Individual", context: "Projeto pessoal", story: ["Depois de usar o Convex para alertas em tempo real no meu projeto final de licenciatura e de ter gostado, quis ver como o Firebase resolve o mesmo problema. O resultado foi o Live Notes, um quadro partilhado onde todos veem as notas a aparecer, mover e mudar no momento. Começou de forma simples e, com a ajuda de IA, fui-o transformando no canvas que é hoje, com zoom, deslocação, um minimapa e notas que se podem arrastar para qualquer lado.", "A Realtime Database do Firebase mantém um WebSocket aberto com cada visitante e envia as alterações assim que são escritas, pelo que cada cliente escuta o quadro em vez de pedir atualizações. A presença usa a mesma ligação, com o Firebase a remover a pessoa automaticamente quando a ligação cai. Como a aplicação já estava no Firebase, usei o seu início de sessão com Google para as contas, enquanto os convidados podem entrar de forma anónima, e os nomes de utilizador são reservados com transações para que duas pessoas nunca fiquem com o mesmo.", "As edições passam por rotas no servidor que as validam, e cada gravação leva o texto em que se baseou, para que uma edição em conflito seja detetada em vez de apagar silenciosamente o trabalho de outra pessoa. As alterações por gravar ficam numa fila que sobrevive a recarregamentos e separadores fechados, e as regras de segurança da base de dados têm os seus próprios testes."] },
  },
  "sns-hospitals": {
    en: { role: "Co-developer", team: "2 people", context: "University class", story: ["I built this with a classmate for a mobile development class at university, over two phases, each with its own set of requirements. We mostly built it together. Sometimes one of us took charge of a screen or of getting a specific test to pass, but we reviewed each other's code, suggested improvements, and designed the interface by pitching ideas for what to add and how to present the information.", "We used the Repository pattern in a layered architecture. The interface only talks to a repository, which sits in front of two data sources, the SNS API and a local SQLite database, and decides which one to use based on connectivity. That keeps the app working offline and the business logic out of the widgets.", "Dependencies are injected with Provider, a widely used approach in Flutter. The data sources and device services, like location and connectivity, are defined as interfaces and registered once at startup, and screens get them from the widget tree instead of creating them. When we changed a data source or added features in the second phase, we only had to touch one layer, not the whole app."] },
    pt: { role: "Co-desenvolvimento", team: "2 pessoas", context: "Cadeira universitária", story: ["Desenvolvi esta aplicação com um colega de curso para uma cadeira de desenvolvimento mobile, ao longo de duas fases, cada uma com os seus requisitos. Construímo-la sobretudo em conjunto. Às vezes um de nós ficava responsável por um ecrã ou por pôr um teste específico a passar, mas revíamos o código um do outro, sugeríamos melhorias e desenhávamos a interface a lançar ideias sobre o que acrescentar e como apresentar a informação.", "Usámos o padrão Repository numa arquitetura em camadas. A interface fala apenas com um repositório, que fica à frente de duas fontes de dados, a API do SNS e uma base de dados SQLite local, e decide qual usar consoante a conectividade. Assim, a aplicação continua a funcionar sem Internet e a lógica de negócio fica fora dos widgets.", "As dependências são injetadas com o Provider, uma abordagem muito usada em Flutter. As fontes de dados e os serviços do dispositivo, como a localização e a conectividade, são definidos como interfaces e registados uma vez no arranque, e os ecrãs obtêm-nos da árvore de widgets em vez de os criarem. Quando mudámos uma fonte de dados ou acrescentámos funcionalidades na segunda fase, bastou mexer numa camada, e não na aplicação inteira."] },
  },
};

export function getProjectStudy(project: Project, language: "en" | "pt") {
  const translations = language === "pt" ? pt : en;
  return {
    ...translations.projects.items[project.slug as keyof typeof translations.projects.items],
    ...studies[project.slug as keyof typeof studies][language],
  };
}

export const studyLabels = {
  en: { back: "All projects", role: "Role", team: "Team", context: "Context", stack: "Stack", gallery: "Screenshots", light: "Light theme", dark: "Dark theme", screen: "Application preview", full: "Open full-size screenshot", next: "Next project", previous: "Previous project", projects: "Projects", visitProject: (title: string) => `Visit ${title}`, tryProject: (title: string) => `Try ${title}`, source: "View source", collaboration: en.projects.collaborator_repository },
  pt: { back: "Todos os projetos", role: "Papel", team: "Equipa", context: "Contexto", stack: "Tecnologias", gallery: "Capturas de ecrã", light: "Tema claro", dark: "Tema escuro", screen: "Pré-visualização da aplicação", full: "Abrir captura em tamanho original", next: "Próximo projeto", previous: "Projeto anterior", projects: "Projetos", visitProject: (title: string) => `Visitar ${title}`, tryProject: (title: string) => `Experimentar ${title}`, source: "Ver código", collaboration: pt.projects.collaborator_repository },
};
